spinnaker/fiat

fiat-core/fiat-core.gradle, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/AccountProvider.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/ApplicationProvider.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/FileBasedApplicationProvider.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/providers/AccountProviderSpec.groovy, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/providers/FileBasedApplicationProviderSpec.groovy, fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/AccountConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ApplicationConfig.java
Based off of #10 , so please only review the **last** commit.
The intent is to get these app configs moved into an S3/GCS bucket, but starting with a file-based approach helps prove out the concepts.
A user's `fiat-local.yml` file would contain something like:
```
applications:
fileBased:
directory: /home/ttomsu/.spinnaker/appConfigs
```
where admins of the system would drop in files like `my-app.config` that look similar to how account configs are structured:
```
name: my-app
requiredGroupMembership:
- my-app-users
```
Eventually we'll get to the point where these files will be generated when an app is created in the UI and uploaded into the configured storage bucket, where it can be versioned and watched for changes by all Fiat instances. 
@cfieber @ajordens @duftler @jtk54 PTAL
=> Adds ApplicationProvider interface and file watching implementation.

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/ServiceAccount.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsResolver.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/ServiceAccountProvider.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/providers/ServiceAccountProviderSpec.groovy, fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ServiceAccountsConfig.java
This is based off of #11, please only review the **last** commit.
Introduces the Fiat service account - a mechanism to allow automated/triggered pipelines to access protected resources. 
Because it is itself a group, only users who belong to the service account group will be able to see that it exists and to use it. This is reflected in the returned UserPermission object:
```
ttomsu@blinky:~/.spinnaker/appConfigs$ curl http://localhost:7003/authorize/ttomsu@spinnaker-test.net | pjs
{
"cloudResources": {
"accounts": [
{
"authorizations": [
"READ",
"WRITE"
],
"name": "my-protected-account"
},
{
"authorizations": [
"READ",
"WRITE"
],
"name": "my-aws-account"
}
],
"applications": [
{
"authorizations": [
"CREATE",
"READ",
"WRITE"
],
"name": "abc"
}
]
},
"name": "ttomsu@spinnaker-test.net", …
```
=> Adds service account concept and static config setup, impl.

README.md, build.gradle, fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/config/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationFilter.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-core/fiat-core.gradle, fiat-core/src/main/java/com/netflix/spinnaker/fiat/config/RetrofitConfig.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/ServiceAccount.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Authorizable.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Viewable.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/ResourceSpec.groovy, fiat-web/fiat-web.gradle, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, settings.gradle
The `fiat-api` module is a shared library that can be used by all of the other Spinnaker microservices to check if a user is authorized to view a particular resource.
The module defines the necessary pieces for Fiat integration, including: 
* A `Filter` to pull the Spinnaker username and put it into the Spring Security context.
* A Spring Security `PermissionEvaluator` that is used by the `PreAuthorize` and `PostFilter` annotations that will go on the secured endpoints.  
* A Retrofit interface for (strongly typed!!) REST calls going to Fiat.
* A config files to make it all work out-of-the-box when the `fiat-api` library is included in the classpath.
This is a relatively big PR, but I've broken it down into common commits for easier reviewability. Notes on the non `fiat-api` commits:
1.) …
=> Introduction of fiat-api module.

fiat-api/src/main/java/com/netflix/spinnaker/config/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsRepository.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
This change enables other services (such as Front50) to invoke an update on a subset of users when a new resource is created (such as an application). It uses the reverse index of roles created in https://github.com/spinnaker/fiat/pull/60 to make the operation fast. 
Also creates a Logger to match the output of the rest of the logging output.
@jtk54 @duftler @ajordens @cfieber PTAL
Closes https://github.com/spinnaker/fiat/issues/51 after cutting a release.
=> Updates RolesController to accept a set of roles to update.

fiat-web/pkg_scripts/postUninstall.sh
I was looking through the project structure for help starting Halyard, and realized this file here probably doesn't do what it's intended to do.
@ttomsu
=> Don't delete clouddriver when uninstalling fiat

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/ResourceProvidersHealthIndicator.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/UnrestrictedResourceConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionResolutionException.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/RolesControllerSpec.groovy
Fixes https://github.com/spinnaker/fiat/issues/46
Fiat is heavily dependent on Front50 and Clouddriver to get bootstrapped data. Previous efforts ensured Front50 was up in order to resolve service accounts, and included a HealthIndicator to the load balancer to ensure traffic wasn't sent until Fiat was able to connect to all resource providers.
Health checks aren't really helpful enough for single instance and/or load-balancer-less development, especially if Front50 was up, but Clouddriver down, because there was minimal logging indicating a problem.
The solution is to multi-fold:
* Merge and simplify the UserRoleSyncer's `updateServiceAccounts` with its `updateUserPermissions`.
* Changes the `PermissionResolver` interface to throw exceptions instead of returning `Optional`, because it …
=> Improves startup behavior when dependent services are down.

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverService.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy
Depends on https://github.com/spinnaker/clouddriver/pull/1115
Uses unrestricted getAllApplications endpoint from Clouddriver to operate on the _complete_ list of Spinnaker applications.
@jtk54 @duftler @ajordens @cfieber PTAL 
/cc @gbougeard
=> Adds Clouddriver as source of applications.

fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/config/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/config/FiatClientConfigurationProperties.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java
... Gate's FiatService endpoints into fiat-api's shared version.
This PR also fixes an issue with the FiatService currently in Gate (https://github.com/spinnaker/fiat/issues/102), but I can't mark that bug as closed until this PR is released and Gate is updated to use the newly released `fiat-api` module.
@duftler @jtk54 @ajordens @cfieber PTAL
=> Makes fiat-api module Gate friendly. Most notably this PR merges in

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationFilter.java
I see logs where the cache calls of various other components (gate, echo, etc) get rejected for user 'ignored2'. 
@jtk54 @duftler PTAL
=> Make anonymous user principal be 'anonymous'

build.gradle, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java, fiat-ldap/fiat-ldap.gradle, fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/config/LdapConfig.java, fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java, fiat-web/fiat-web.gradle, settings.gradle
This enables Fiat to connect to an LDAP server to search for groups.
I attempted to write a test with an embedded LDAP server, but aparently ApacheDS uses an older, incompatible version of SLF4J, and I couldn't get it working.
PTAL @duftler @jtk54 
cc @scotmoor @rguthriemsft @ajordens @cfieber 
tag https://github.com/spinnaker/fiat/issues/30
=> Adds initial LDAP UserRoleProvider

Dockerfile, Dockerfile.slim, cloudbuild.yaml
This PR drops the generated docker container from 533MB to **270MB**, and if using Google Cloud Builder (via cloudbuilder.yaml), it shrinks even further to **113.6MB** (which is basically Alpine container + Java 8 JRE + Fiat binary & libs).
I still have to ensure the thing actually _runs_, but at least it's building successfully. Will tackle that piece tomorrow.
@cfieber @duftler @skim1420 @lwander
=> Slims container by deleting compile-time requirements.

fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
Create an endpoint to only fetch a user's roles - this makes it possible to get only the roles for a user without having to fetch the whole information as in the endpoint `getUserPermission`. Slightly more performant.
=> Add endpoint to fetch user's roles

fiat-api/src/main/java/com/netflix/spinnaker/config/FiatAuthenticationConfig.java
Because Spring Security autoconfiguration happens early, current way of autoconfiguring FiatService will fail in later versions of Spring Boot. Instead, create a ObjectMapper on the fly to support creation.
=> Fix startup issue with FiatService

fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
This PR introduces a new cache of UserPermissions for users of the Fiat API module. It stores the whole permission for 20s (by default), even if the request could be serviced by a simple authorize call. This is the first step to scaling Fiat to a NFLX sized deployment.
This also means we no longer store the whole permission in the `Authentication` object.
@cfieber @jtk54 PTAL
=> feat(api): Adds shared cache of user permissions.

fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
fix a problem treating URIs that end with `.com` as a request for content-type
`application/ms-download`
turns out some people have email addresses that end with `.com` [1]
[1] - @cfieber, just now
=> fix(service): disable content negotiation via URI path extension

fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/config/LdapConfig.java, fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java
Exposes additional spring-security fields for the LDAP configuration that allow resolving the user via search instead of a user DN template.
In response to #30, with more detailed additional discussion [here](https://github.com/spinnaker/fiat/issues/30#issuecomment-289835132). Also created a PR for gate which adds the same fields for authn (https://github.com/spinnaker/gate/pull/369).
=> feat(authZ/ldap): Adds userSearchBase and userSearchFilter properties for LDAP

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultAccountProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverApi.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/Front50Api.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/Front50Service.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultAccountProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java
A subsequent change will make use of the wrapper classes to provide some temporary caching/
circuit breakers/fallbacks around calls to clouddriver and front50
=> refactor(rpc): Introduces a wrapper around Retrofit APIs.

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ServiceAccount.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/ProviderCacheConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/ResourceProvidersHealthIndicator.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultAccountProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/HealthTrackable.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ProviderHealthTracker.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/BaseProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/ProviderHealthTrackerSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/FiatSystemTestSupport.groovy, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/RolesControllerSpec.groovy, fiat-web/src/test/resources/fiat.properties
Also pulls out provider health into it's own class, and caches response from
all resource providers for 20s.
As discussed in https://github.com/spinnaker/fiat/issues/164, this PR simplifies services accounts to just:
```
{
name: foo,
memberOf: [bar, baz]
}
```
additional tags: https://github.com/spinnaker/fiat/issues/163
PTAL @jtk54 @cfieber
=> feat(serviceAccounts): Simplifies service accounts.

fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java, fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GithubTeamsUserRolesProvider.java
While setting up spinnaker on kubernetes using github for authentication and authorization we ran into the problem that fiat made too many requests to the github api, eventually running into rate limit restrictions making the spinnaker installation useless at that point.
This PR adds a cache to the problematic request to fix the problem temporarily.
Moving forward the attempt should probably be to reduce the amount of calls in the first place so that no such cache is necessary anymore.
=> fix(authz/github): Add cache to team membership check to prevent excessive http requests

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/CatsSchedulerConfig.java
The github agent takes longer when there's more users/teams added, so we're seeing it take 12 seconds to run the agent now.
However the lock is set to expire after 10 seconds. 
This will allow another agent to run again. If there's multiple agents, it'll round robin until there's no more remaining API rate limit calls left. Github allows 5000 calls / hour.
Let's wait 30 seconds by default after the poll interval before allowing another instance of fiat to be the poller.
=> fix(UserRoleSyncer) a poll could take longer than 10 seconds

fiat-web/fiat-web.gradle
bootRepackage flag was using string interpretation of groovy truth
=> fix(build): fix fiat-web to build normal jar

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java
regularly seeing a PUT `/roles/anonymous` with payload `["anonymous"]` (I think this is from /health endpoints or something being polled by ELB)
Without this change, that PUT request clears out all the `__unrestricted_user__` authorizations effectively nuking the anonymous permission set.
=> fix(authz): ensure anonymous role is not cleared

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ServiceAccount.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Viewable.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/FiatAdminConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourceProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/BaseProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProviderSpec.groovy, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
A quick summary of how it works is:
In the fiat configuration file, it will be possible to set a list of groups that will have admin capabilities.
```
fiat:
admin:
roles: 
- sre_team
- security_team
```
This will be merged with the permissions in each permissioned object (applications, accounts and service users). Members belonging to a group that is configured as Admin, have no restrictions in Spinnaker - meaning that they can access and change any resources.
The above example will mean that `sre_team` and `security_team` will have access (to view and to modify) to everything in Spinnaker.
Feedback is highly appreciated, thanks!
=> feat(admin) Add admin functionality to fiat

fiat-web/etc/init/fiat.conf
Changing to appending to the log file so logs will correctly rotate.  This prevents large amounts of null data at the start of a rotated log file.
=> fix(fiat/log): Append to log instead of overwrite

fiat-web/pkg_scripts/postInstall.sh
fix(install):  fix log dir
deb package created clouddriver dir on install, this makes the fiat log dir instead.
=> create fiat log dir on package install instead of clouddriver.

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
I tested this on my local setup. Before this fix, application names with dashes in them would return a 403 from Gate. Post this change, they work fine.
Clouddriver, Orca, Gate, and Front50 all need to be updated to the new version of fiat-api for this fix to work.
spinnaker/spinnaker#2513
=> fix(api): Stop parsing application names in fiat using frigga.

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverService.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/Front50Service.java
If Hystrix times out the command, `cause` is `null`. Hystrix gobbles the NPE and just rethrows the timeout, so we lose the fallback behavior.
=> fix(hystrix): prevent silent NPE after timeout

build.gradle, fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatServerConfigurationProperties.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
This PR handles the case where a user attempts to access a service
directly without going through `gate`.
It is a common operational requirement to be able to access internal
APIs directly.
- bump spinnaker-dependencies to suppress 404 stack traces
- emit a metric from `getPermission` vs a debug log message
=> feat(web): Support defaulting to `__unrestricted_user__` when no permissions found

build.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
During login we want to read a fresh view of the permission
from fiat to support populating allowed accounts headers.
Also some cleanup in FiatAuthenticationConfig for easier autoconfigging.
=> fix(authn): invalidatePermission from cache

fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationFilter.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
This PR re-orders how the `FiatAuthenticationFilter` is inserted into
the http chain.
Previously when management security was disabled, the caller was
redirected to `/login`.
- introduce a metric to track how often the unregistered user fallback is hit
- support dynamically disabling the permission evaluator
=> feat(api): Support running with `management.security.enabled: false`

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationFilter.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatStatus.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
This PR will always register the `FiatAuthenticationFilter` in the
authentication chain _but_ allow for it to be disabled at runtime
depending on the dynamic config service.
The `FiatAuthenticationFilter` has been modified to no-op when
fiat would have previously been disabled.
A metric is also emitted (`fiat.enabled` to track whether fiat is
enabled on a service/instance basis).
=> feat(api): Support enabling fiat at runtime

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/LockConfig.java
This avoids a potential runtime issue wherein there are 3 or more
different object mappers to choose from.
=> fix(core): Explicitly create `ObjectMapper`

fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
Needed for spinnaker/front50#329 and spinnaker/spinnaker#2948
=> fix(authz/api): Perform a full sync on empty specificRoles input

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
=> fix(roles): Stop syncing if list of users is empty.

build.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatStatus.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/RetrofitConfig.java
Should `fiat` ever be unavailable, this supports a fallback to a
`UserPermission` that is constructed based on the contents of
the `AuthenticatedRequest`.
In the event of a legacy fallback, access to _all_ applications will be
explicitly granted.
It is not on by default and must be explicited opt'd enabled via:
```
fiat:
services:
legacyFallback: true
```
or by setting the `fiat.legacyFallback.enabled` dynamic property.
=> feat(core): Support a fallback to legacy account permissions

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ProviderHealthTracker.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverService.java
Cuts down on the number of calls to clouddriver for metadata that does
not change all that frequently.
Noticed a fairly high volume of calls falling through from x509
authentication attempts, more than seemed reasonable.
=> fix(roles): Introduce cache / short refresh around clouddriver calls

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatServerConfigurationProperties.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
An unknown application is one that does not have explicitly specified
permissions. It may exist in `front50` or it may not.
Can be enabled by `fiat.allowAccessToUnknownApplications: true`.
=> feat(core): Support allowing default access to all unknown applications

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
Adds retry support for calls to fiat in FiatPermissionEvaluator
Invalidates cached users if they contain legacyFallback permissions
=> feat(api): FiatPermissionEvaluator reliablity

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy
This flag was originally added to allow sites with large numbers of
applications to avoid needlessly serializing the same set of applications
for each user.
Unfortunately it doesn't play nice when an application was explicitly
filtered out because a user was not granted access to it!
This PR will no longer filter applications but rather include them in
the permission with _no_ authorizations.
It only applies when `allowAccessToUnknownApplications` is enabled.
```
[
{
"name": "clouddriver",
"authorizations": [
"READ",
"WRITE"
]
},
{
"name": "orca",
"authorizations": [
]
}
]
```
vs
```
[
{
"name": "clouddriver",
"authorizations": [
"READ",
"WRITE"
]
}
]
```
=> fix(roles): Avoid filtering when `allowAccessToUnknownApplications` is enabled

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandler.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
In response to user feedback that seeing just a `403` error lacked
sufficient context to determine exactly what permission was lacking,
particularly when a pipeline or orchestration failed.
The chosen response messaging mimics what clouddriver is already
doing.
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidator.groovy#L29
```
{
"error": "Forbidden",
"message": "Access denied to application clouddriver",
"status": 403,
"timestamp": 1534222128232
}
```
=> feat(api): Surface context around what resource was denied access

fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java
For the LDAP provider, we were overwriting external roles if they were already set. This resulted in fiat service accounts getting synced with no roles at all.
Huge thanks to @emptywee for helping debug this!
@lwander we should cherry pick this into 1.9
Fixes https://github.com/spinnaker/spinnaker/issues/3214
=> fix(ldap): Return a new ExternalUser from multiLoadRoles in LDAP

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy
Delegates loading to the `UserRolesProvider` with the default remaining
an empty set.
We have a custom `UserRolesProvider` at Netflix and would like the
ability to specify one or more additional roles for the anonymous user.
=> feat(roles): Configurable `__unrestricted_user__` roles

README.md, build.gradle
Starting fiat with ./gradlew -DDEBUG=true now causes the JVM to listen for a remote debugger on port 7103.
=> chore(build): add debug flag to fiat build

fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java
Cherry-pick of https://github.com/spinnaker/fiat/pull/269 into Spinnaker 1.10
Fixed UnsupportedOperationException for service accounts which DO NOT exist in User Role Provider Service (e.g: LDAP)
=> fix(ldap): Return mutable list to support "addAll" operation (#269)

README.md, fiat-web/fiat-web.gradle, gradle.properties, settings.gradle
Allows building Fiat with only a subset of role providers. Defaults to all providers
=> Modular builds

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/RedisConfig.java
JedisPoolConfig also sets minEvictableIdleTimeMillis to 60 seconds for this pool. Leaving it to `public static final long DEFAULT_MIN_EVICTABLE_IDLE_TIME_MILLIS = 1000L * 60L * 30L` is too long. 
The idle connection will be kept on client side, but may be closed by server timeout configuration. One of our customers just met this issue, raise this pull request for his benefit.
We construct the object of GenericObjectPoolConfig in Jedis-related code on rare occasions.
=> fix(redis): New a JedisPoolConfig instead of GenericObjectPoolConfig

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/FiatRoleConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProviderSpec.groovy
The current logic of service accounts is that if the service account is member of group a and b, the user that wants to use the service account needs to be a member of group a AND b. This patch changes this AND to an OR.
The rationale behind this is that when we have applications that are managed by multiple teams, they should be able to use a service account in the trigger and edit the pipelines without requiring the one to edit the pipelines to be a member of all the teams involved.
To enable this behaviour one sets `fiat.role.orMode=true` in the fiat
configuration
This is an opt in version of https://github.com/spinnaker/fiat/pull/229
=> feat(serviceAccounts/orMode): Change group behaviour of service accounts

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatStatus.java
The ability to dynamically turn fiat off/on was convenient during initial
rollout but can be a security risk in a production environment.
Set `services.fiat.refreshable: false` to disable.
=> feat(api): Support turning off dynamic refreshing of fiat status

fiat-web/src/test/groovy/com/netflix/spinnaker/config/EmbeddedRedisConfig.groovy, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/RolesControllerSpec.groovy
Embedded redis is currently defined as a prototype bean in the test config; this means that a new embedded redis will be generated any time a redis is need in the auotwiring config. We're currently only destroying one of them (the one directly asked for in the test class). Instead, make this a singleton bean with a spring-managed destruction method, and use the same bean everywhere.
=> fix(redis): Fix leaked embedded redis from tests

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
Doing a full sync of all roles takes a linear amount of time with respect to the number
of users. This patch only updates the users that are affected by a role change. If no roles
are specified, then a full sync is done as we were doing before.
=> chore(syncroles): Improve partial sync of roles

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
When using Fiat, I keep tripping up and fetching the authentication from within another thread via `SecurityContextHolder.getContext().getAuthentication()`, which gives me a null authentication object.
Kork provides a `AuthenticatedRequest.getSpinnakerUser()` mechanism to get the username, so I've been creating an anonymous overriding horrible Authentication object to pass to Fiat. But Fiat just cares about the username, so...how about a method that just takes that?
=> feat(permissions): allow username string to be passed to hasPermissions

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
The previous implementation is used in some Front50 batch APIs so we can't get rid of it just yet!
=> feat(admin): Implement isAdmin check in FiatPermissionEvaluator.

build.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-roles/fiat-roles.gradle, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/RedisConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/MainSpec.java, fiat-web/src/test/resources/fiat-test.yml
updates to latest spinnaker-dependencies version
=> merge master into boot2 branch

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
Recent testing of our legacy fallback support did not actually work
correctly when `fiat` was unavailable.
The original intention of `legacyFallback: true` was to support a
fallback to the authorization model that existed pre-fiat.
This model only supported WRITE restricted accounts and expected that
the authorization context was propagated between services with the
`X-SPINNAKER-*` headers.
This PR is an attempt to do a better job for manually triggered pipelines
(which should have some accounts specified) as well as read operations
performed via the UI.
=> feat(api): Allow access to unknown applications when legacyFallback=true

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/Front50Service.java
This reverts commit 4ea2d71a717b2366acae34170823596ccf43dcc4.
Having this cache along with the cache in `BaseProvider` was causing a lot of user role syncs to use stale data from Front50. This should alleviate the problems in 1.13 e.g. https://github.com/spinnaker/spinnaker/issues/4276
Ideally, I think we should try to refresh the `BaseProvider` cache with live data before a role sync starts but I'll make that a follow up PR.
=> Revert "fix(front50): Update Front50 cache periodically and serve live calls from cache. (#351)"

build.gradle, fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatStatus.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-core/fiat-core.gradle, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/Authorization.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/BuildService.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ResourceType.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/ResourceSpec.groovy, fiat-file/fiat-file.gradle, fiat-google-groups/fiat-google-groups.gradle, fiat-ldap/fiat-ldap.gradle, fiat-roles/fiat-roles.gradle, fiat-web/fiat-web.gradle, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java, gradle/buildViaTravis.sh, gradle/init-publish.gradle, gradle/installViaTravis.sh
* removes lots of cargo-culted dependency declarations
* trims dependencies in fiat-core and fiat-api to minimize the
impact consuming projects
* guava caches -> caffeine
=> fix(dependencies): dependency cleanup

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java
Currently these timeouts are inherited from normal service <-> service
communication.
The preference would be that an individual call to `fiat` would timeout
before the overarching service rpc times out.
Shorter timeouts would allow the existing retry behavior in
`FiatPermissionEvaluator` to be more effective.
=> feat(api): Support overriding the connect/read timeouts for `FiatService`

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/Authorization.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy
Only adds the new type. Follow up PRs will:
- Migrate existing applications by adding execute permissions to users who can currently execute pipelines (PR:https://github.com/spinnaker/front50/pull/516)
- Switch to using Execute for checks during a pipeline trigger.
Part of https://github.com/spinnaker/spinnaker/issues/3554
=> feat(roles): Add Execute as a type of Authorization

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
When `service.fiat.legacyFallback` is `true`, this will implicitly allow
access to all build services in the event that `fiat` is unavailable.
=> fix(api): Support `legacyFallback` for `BUILD_SERVICE`

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatServerConfigurationProperties.java
When an application does not explicity specify which groups have
`EXECUTE` permission, add `EXECUTE` permissions to groups that have
`READ` or `WRITE` based on the value of `fiat.executeFallback`. For
backwards compatibility, `fiat.executeFallback` defaults to `READ`
i.e. groups that have `READ` on an application will now have `EXECUTE`
as well.
Part of spinnaker/spinnaker#3554
=> feat(roles): Add execute authz when its missing.

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
This PR preserves the debouncing capability of the existing
permissionsCache but attempts to provide a fresher fallback in the
event that a "no accounts" fallback was previously cached.
The "no accounts" fallback will result if the X-SPINNAKER-* headers
are not propagated for a given api request (or that api request
originated from an scheduled system operation and thus was not
authenticated to begin with).
=> fix(api): Rebuild the legacy fallback if it has no account grants

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy
This PR addresses an issue where `ensureExecutePermission()` was not
getting invoked when `allowAccessToUnknownApplications` was true.
=> feat(roles): Handle `allowAccessToUnknownApplications` when determining `EXECUTE`

fiat-web/src/main/java/com/netflix/spinnaker/fiat/Main.java
Fixes spinnaker/spinnaker#4346.  When we discussed a couple of weeks ago, I didn't realize there was a way to turn of the health indicator from the code (rather than from config).  Given it's possible to do that, it's probably easier to do this and then revert it once we pull in the upstream fix.
There is currently an NPE in the LDAP health indicator that has been fixed but not yet released which is causing fiat to never appear healthy. Until we can pull in the upstream fix, disable the LDAP health indicator.
=> fix(ldap): Disable LDAP health indicator

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
When syncing roles, Fiat recomputes unrestricted roles for all the apps. Apps are cached for 20s (by default). This causes issues when creating an app (which will also do a sync) within 20s of another sync: the new app will not be reflected in the unrestricted role and result in 403s.
This fix clears the cache of the various providers to ensure they're refetched from Front50/Clouddriver.
This should address https://github.com/spinnaker/spinnaker/issues/4421
=> fix(apps): Clear resource provider caches to ensure up-to-date data

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/RedisConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, gradle/wrapper/gradle-wrapper.properties
Fixes redis interactions in RedisPermissionRepository that can result in
depleting the redis pool.
Specifically:
* converts smembers calls to sscan calls, and gets/returns an object
from the pool to do so.
* removes nested calls to redisClientDelegate that were holding on
to pool objects
* partitions lookup of users into smaller batches
* partitions role lookup
Additionally, uses InstrumentedJedisPool to enable metrics collection
on redis interactions.
=> fix(redis): mitigate JedisPool depletion

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/IgorService.java
Otherwise we keep polling it and it can still contribute to fiat
reporting that it is not healthy.
=> feat(igor): only poll igor if it is enabled

build.gradle, fiat-bom/fiat-bom.gradle
compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa
=> fix(bom): Fix generated pom.xml to omit invalid lombok declaration

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
When a param is missing from the `hasPermission` call, log it louder
=> fix(logging): log at higher level for some auth failures

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandler.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandlerSpec.groovy, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatSharedSpecification.groovy
This is the first part of the change to improve front50's access denied error messaging.  After this change we will replace front50's `AccessDeniedExceptionHandler` with `FiatAccessDeniedExceptionHandler`.
Here are examples of the different error message contexts:
```
//Non service account example:
{
"timestamp": "2019-09-25T18:41:21.833+0000",
"status": 403,
"error": "Forbidden",
"message": "Access denied to application smalleytest - required authorization: WRITE"
}
//Service account example:
{
"timestamp": "2019-09-25T18:44:27.137+0000",
"status": 403,
"error": "Forbidden",
"message": "Access denied to serviceaccount someServiceAccount"
}
```
=> fix(error): Improve access denied error messaging

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/Authorization.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/AccessControlledResourcePermissionSource.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/AggregatingResourcePermissionProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultAccountResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultBuildServiceResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultResourcePermissionProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/Front50ApplicationResourcePermissionSource.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ProviderException.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourcePermissionProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourcePermissionSource.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/BaseResourceProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProviderSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/DefaultResourcePermissionConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
Adds a ResourcePermissionSource - a place to get permissions from, and
ResourcePermissionProvider - the API for callers
The default ResourcePermissionProvider is an aggregator across all
ResourcePermissionSources
There is a `DefaultResourcePermissionConfiguration` that maintains the
status quo by providing default implementations that simply read the
permissions directly off of the objects, but allows opting out of some
or all of the default opinions if someone wants to customize, extend,
or override any of the default behaviour.
Additional improvements:
* refactor(fiat-roles):
- make DefaultPermissionsResolver immutable
- don't return null values from Permissions#get
- clean up loadAll
closes #478 
closes #472
=> feat(aggregator): enables customization of permission aggregation as well as permission sources

fiat-roles/fiat-roles.gradle, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverService.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/Front50Service.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/IgorService.java
Will suppress all the `Request GET:http://<service>/<endpoint> is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous` messages that is currently spamming the Fiat log.
=> fix(roles): Allow anonymous calls from Fiat to other Spinnaker modules

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/Authorization.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultResourcePermissionProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/Front50ApplicationResourcePermissionSource.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatServerConfigurationProperties.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
**This implementation is still in draft state**. It achieves the following:
1. Add a configuration parameter called `restrictApplicationCreation`. If set to false (the default), this feature will be ignored.
2. Add a `CREATE` authorization.
3. Call the `ResourcePermissionProvider` immediately from `AuthorizeController`, because creation permissions are typically dynamic, and cannot be known before the application is submitted for creation. Thus, they cannot be held on the UserPermissions object.
4. Make `Front50ApplicationResourcePermission` source strip out any `CREATE` permissions provided on the source, because it doesn't make sense for users to add `CREATE` permissions on the resource they are creating, and it will basically work against any other authorization model we try to …
=> feature(authorization): Add creation access control

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy
This reverts a well intended change where the resulting Permissions object always had an entry for each Authorization type. This change makes rolling out new values in this enum painful to coordinate across services.
This reverts the behaviour to now only store an explicit entry in the Map if there are specifically roles defined for that Authorization type
=> fix(api): fix serialization issues with new Authorization enum values.

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java
Deprecates instead of removes isEmpty() on Permissions, and delegates it to check isRestricted
rather than the Map content.
=> fix(fiat-api): revert breaking change to Permissions.

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy
The unrestricted user can have associated roles via
`UserRolesProvider.loadUnrestrictedRoles`, however this would
always short-circuit evaluation of permissions for those roles.
This resulted in the case where on the first authorization
(`POST /roles/:userId`) the user would not have access to any
resources that were granted solely via the unrestricted role.
However in a subsequent authentication - the users permissions
would get merged with an existing user entry and the unrestricted
roles would show up as if they were directly granted to the user
(due to thge way the `UserPermissions.merge` happens in the
`RedisPermissionRepository`) and eventually the resources protected
by unrestricted roles would show up.
=> fix(unrestricted): load permissions for unrestricted roles

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
Retrofit methods cannot have a `void` return type. We either need to provide a return type, or a callback. This fixes the following exception:
```
java.lang.IllegalArgumentException: FiatService.canCreate: Must have either a return type or Callback as last argument.
```
I also added `canCreate` to the path, because it makes more sense.
=> fix(authorization): canCreate should not return void

fiat-file/src/main/java/com/netflix/spinnaker/fiat/roles/file/FileBasedUserRolesProvider.java, fiat-file/src/test/groovy/com/netflix/spinnaker/fiat/roles/file/FileBasedUserRolesProviderSpec.groovy
When calling `loadRoles` of file-based roles. I am faced with a `NullPointerException` if the user is not defined in the file. I fixed this to return an empty list instead.
This is a valid use-case for implementations that use external roles (SAML for example), but want to provide specific roles for some users.
=> fix(roles): file-based roles fail when the user is not provided in the file

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ServiceAccount.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/ServiceAccountSpec.groovy
Roles can't be empty. This leads to unexpected behaviour. However, we
were allowing creating empty roles like "" or "   " on the pipeline
triggers (via API), which made service users to contain invalid roles
and thus failing on every sync request that tries to map roles to accounts.
This rendered FIAT unusable to get permissions and subsequently not
allowing any authorization operation.
This patch sanitizes the input on ServiceAccounts so we make sure
that the roles considered are valid.
=> fix(serviceAccount): Filter non-valid roles when converting to UserPermission

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ApplicationResourcePermissionSource.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/AggregateResourcePermissionConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/DefaultResourcePermissionConfig.java
Additionally, rename Front50ApplicationResourcePermissionSource to ApplicationResourcePermissionSource and adjust config accordingly.
This way, if default permission source objects contain logic then they will operate after any logic contained in an aggregate permission source (if order is specified correctly).
Specifically, we want to process `EXECUTE` permissions last in the chain of aggregate permission sources since if a resource is missing `EXECUTE` permissions it falls back to the configured permission type (defaults to `READ`).
=> fix(permissionSource): Set order (lowest precedence) on default permission sources

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultFallbackPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/FallbackPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/AggregatingResourcePermissionProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ApplicationResourcePermissionSource.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationResourceProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultFallbackPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/DefaultResourcePermissionConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
I misread the logic for the aggregate permissions resolver - we will need to resolve fallback permissions after everything has been built up.  I tried to do this in a way that would allow us to configure other fallback resolvers if need be.
=> refactor(fallback): Add FallbackPermissionsResolver and default implementation

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandler.java
Because this is often the only AccessDeniedException handler registered in services, it can be difficult to know exactly what caused the exception.  This should help.
=> chore(log): Log request method, URI, and exception in FiatAccessDeniedExceptionHandler

fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
Debugging an intermittent access denied error to accounts.  CaffeineStatsCounter pushes cache metrics to the registry and the debug log might give us a bit more insight.
=> fix(metrics-logs): Record permissionsCache caffeine metrics with CaffeineStatsCounter and add debug log when access denied to accounts

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
Fixes a potential race condition persisting user permissions where previously we would
remove the entire set of permissions for a resource, then write the current set. This
changes to only remove the permissions if the updated UserPermission is empty for that
resource type, so that an API request to load that UserPermission that overlaps with
a refresh of the UserPermission in redis doesn't get less data than it should
=> fix(redis): only remove a key if it wouldn't be overwritten

.github/workflows/pr.yml
The equivalent Travis CI build wasn't running it.
=> fix(ci): remove 'javadoc' from PR build

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationResourceProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/RolesControllerSpec.groovy
This PR completes a small detail that was left over from PR https://github.com/spinnaker/fiat/pull/564 (it was actually merged, even tho shows as closed).
When FIAT requests "all applications" from front50, it actually wants them all - fiat will then apply any "filtering" due to restrictions. That's fiat's job, right? 😅
=> fix(applications): (2nd PR) Do not apply permissions when building the internal model of apps

Dockerfile.compile
I missed this one apparently when I was switching them all in response
to a code review comment.
=> chore(compile): switch to the openjdk container

fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/ControllerSupport.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
A call to decode the input is not necessary since Spring decodes the path variable input by default.  See Spring's RequestMappingHandlerMapping and UrlPathHelper.  For example, a call to
fiat `/authorize/some%2Buser%40example.com` is properly decoded as `some+user@example.com` by Spring, but then decoded again via `ControllerSupport` -- the result is `some user@example.com`.  This can, in certain scenarios, cause authorization lookups to return a 404.
=> fix(decode): Remove duplicate url decoder in ControllerSupport

.github/workflows/release.yml
This way, when it fails (as it will) we can just retry it without re-running the entire build.
=> fix(build): Bump dependencies as a separate job

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/ProviderCacheConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultFallbackPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseResourceProvider.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/DefaultResourcePermissionConfig.java
ensure we read the base resource permission first so other permission sources that augment Permissions
are processed afterword
also adds a scheduled refresh to the BaseResourceProvider cache to ensure a user request doesn't hit
a cache expiration and have to wait for the cache reload
=> fix(permissions): update order annotation on sources

.github/workflows/bump_dependencies.yml, .github/workflows/release.yml
Exact same as https://github.com/spinnaker/kork/pull/567
=> chore(build): Break fiat bump dependencies out into separate workflow

fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
adds an expand query parameter to the /auth/:userId/serviceAccounts endpoint that returns each
serviceAccount as a userPermission to allow for contextual filtering
This will enable an endpoint in gate to filter user service accounts by application when populating
the run as user dropdown in the UI to only include service accounts relevant for the application
being configured
=> feat(serviceAccounts): enable loading full service account details for each users serviceAccount

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Dockerfile.compile, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java, gradle.properties
Additional differences:
`UserRoleSyncer` was using `stream.map().count()` to run an operation on each element and then return the number of elements in the stream. But this doesn't work in Java 11 because "An implementation may choose to not execute the stream pipeline (either sequentially or in parallel) if it is capable of computing the count directly from the stream source." The Java 11 docs (unlike the Java 8 docs) [include an explicit example of this exact thing we're doing and why it doesn't work.](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#count())
Fortunately we had to test to catch this. I wonder where else we're doing this... :/
=> chore(java11): Compile with Java 11 (but targeting Java 8)

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationResourceProvider.java
We were trying to dedupe on appname but each system presents them in a different case (front50 upper
clouddriver lower)
=> fix(applications): fix dedupe of front50 and clouddriver apps

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
Cherry-picking part of #630 to `release-1.19.x`
`UserRoleSyncer` was using `stream.map().count()` to run an operation on each element and then return the number of elements in the stream. But this doesn't work in Java 11 because "An implementation may choose to not execute the stream pipeline (either sequentially or in parallel) if it is capable of computing the count directly from the stream source." The Java 11 docs (unlike the Java 8 docs) [include an explicit example of this exact thing we're doing and why it doesn't work.](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#count())
Fixes spinnaker/spinanker#5466
Fixes spinnaker/spinnaker#5687
=> fix(java11): fix Stream#count() use under Java 11

build.gradle, fiat-core/fiat-core.gradle, fiat-web/fiat-web.gradle
If we actually want this dependency, it only needs to live on the web application itself, it inspects config at runtime. This was ending up as a dependency of fiat-api and landing on all the places we autobump fiat-api to.
=> fix(api): remove spring-boot-properties-migrator from fiat-api

fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatServerConfigurationProperties.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
This is primarily a guard against a user with the admin flag (who has access to all service accounts) in a Spinnaker instance with hundreds of service accounts. This endpoint can quickly get up past the point where the request from gate will time out (and fall back to just asking for the unexpanded list).
=> fix(serviceAccounts): limit the number of service accounts to expand

fiat-web/config/fiat.yml, halconfig/README.md, halconfig/fiat.yml
Currently Halyard is appending a default for the redis config to all configs it generates. Let's push this down to the base config so all users get the same defaults and we don't need to append this all the time.
Currently the base config uses 'services.redis.connection' as the default. This doesn't match what is used for other services, nor what is used for the redis connection in other microservices (which use services.redis.baseUrl).
This commit changes this to look at 'services.redis.baseUrl' for consistency. Users who have configured a 'services.redis.connection' property but not 'services.redis.baseUrl' (and who are depending on that rather than just setting redis.connection directly in their gate config) will need to update to account for this change.
=> config(core): Move redis connection default to base config

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandlerSpec.groovy, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-core/fiat-core.gradle, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/BaseAccessControlled.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/BuildService.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ResourceType.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ServiceAccount.java, fiat-roles/fiat-roles.gradle, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
This change allows Fiat to serve / evaluate permissions for arbitrary resources. I've added an example plugin here that demonstrates how it works: https://github.com/spinnaker-plugin-examples/fileResourceProvider. That example is Spring-based. Ideally I'd get this PR merged and then pull out `Resource` and `ResourceProvider` extension points.
The resulting map served from `/authorize/{user}` looks like this:
```
{
...
"extensionResources": {
"my_extension_resource": [{
"name": ...
"authorizations": ["READ", "WRITE"]
}]
},
...
}
```
There's a slight tweak in fiat client code to automatically evaluate authorizations on these resources.
=> Extension Resources

README.md
While SAML groups are documented in [Authorization (RBAC)](https://spinnaker.io/setup/security/authorization/#authorization-rbac), it is missing in the README.md.
=> Add missing user role provider "SAML Groups"

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/RedisConfig.java
Follow Kork's existing pattern and check for presence of `rediss` in
the URI Scheme.
Follow Kork's existing usage of JedisPool() and supply optional
parameter designating if SSL is enabled or disabled.
Related to: https://github.com/spinnaker/spinnaker/issues/5470
Tested with default in cluster redis (no auth or TLS) and `fiat.yml` 
snippet below and mounting in Redis auth token via env var:
```
services:
redis:
baseUrl: rediss://:${REDIS_TOKEN}@master.<snip>.cache.amazonaws.com:6379
enabled: true
redisRo:
baseUrl: rediss://:${REDIS_TOKEN}@replica.<snip>.cache.amazonaws.com:6379
enabled: true
```
=> feat(fiat): Add support for Redis SSL

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
- does less work while holding a redis connection:
- ensure when looking up the unrestricted user, that we don't read the
same values twice from redis
- close the redis connection before deserializing permission objects
- ensures that if we hit the fallback case for a user that was not resolved
we include the unrestricted user's permissions in the resulting UserPermission
=> fix(authorize): fixes for authorize redis and fallback

fiat-roles/fiat-roles.gradle, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy
The unrestricted user is loaded from redis each time a lookup for a user happens, and
this user may end up with a lot of data associated with it if there are a large number
of secured entities set up for anonymous read access.
This saves the step of fetching and deserializing that data if there is a copy cached.
Adds a new last modified key to track (via redis server time) the last time the
unrestricted user was written to redis, and uses that to ensure a reload happens when
the permissions are rebuilt.
=> feat(perf): cache the unrestricted users permissions

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
For sessionless auth such as X509 in gate, there is a debounce option to prevent having to post a login to fiat for each request,
however part of that is determining whether the user is already populated in the hosts permission cache.
This check 404s if the user has not logged in, but in doing so triggers retries with backoffs before a login is posted.
This introduces a new method just to examine the cache without calling through to the loading behaviour on a miss
=> feat(api): allow fiat clients to check if there is a user permission cached

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionRepositoryConfigProps.java
In moving a Value annotation to config properties, the default was changed from spinnaker:fiat to fiat
This switches the default back to its original value
=> fix(redis): fix accidental change of default redis key prefix

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Dockerfile.compile, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java, gradle.properties
After this commit, we can use Java 11 language features and APIs.
I added a single `var` declaration to make it more obvious if any of our various CI systems are misconfigured.
=> chore(java11): Target Java 11.

fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/config/LdapConfig.java, fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java
Reverts #747.
This is done since I'm starting to see issues with this change in one environment that was not caught during the regular testing of the change.
=> Revert "perf(auth/ldap): Limit search object size"

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/ControllerSupport.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/RolesControllerSpec.groovy
Inputs and outputs normalized so that the user ID lookup is functionally case insensitive.
=> fix(permission): Normalize user permission ID and ensure controllers normalize incoming user IDs

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy
At the username dedupe stage, pre-emptively call `toLowerCase()` to ensure that the `dedupedUsernames` set has been case-insensitively deduped.
In our environment some users have mixed-case usernames, which would lead to a "deduped" username set containing (for example) both `jdoe` and `JDoe`.  In this situation, `RedisPermissionsRepository.getAllByRoles()` would crash with:
```
java.lang.IllegalStateException: Duplicate key jdoe (attempted merging values UserPermission(id=jdoe, accounts=[Account(resourceType=account, name=someaccount, cloudProvider=null, permissions=Permissions(permissions={}))], applications=[], serviceAccounts=[], roles=[Role(resourceType=role, name=somerole, source=null)], buildServices=[], extensionResources=[], admin=false) and UserPermission(id=jdoe, …
```
=> fix(roles): ensure usernames are case-insensitively deduped in RedisPermissionsRepository.getAllByRoles()

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseServiceAccountResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountPredicateProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ServiceAccountPredicateProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/BaseResourceProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProviderSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
The existing behavior has been maintained in `DefaultServiceAccountPredicateProvider`.
Alternative implementations can be provided should you have a need for more
granular or custom behavior.
Access to a service account will be granted _if_ any predicate allows it.
=> feat(roles): Support for more flexible control over service account access

fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
`fiat` has multiple `@Scheduled` functions and the default single-threaded
task execution likely isn't able to keep up.
This PR changes the default to `5` but can be overriden with:
```
fiat:
scheduler:
poolSize: 10
```
=> fix(web): Override the default `TaskScheduler`

fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
Need to clear the SecurityContext in between test runs to isolate
test behavior. (Discovered in experimenting with some changes in
kork to support custom Authentication tokens)
=> fix(tests): test state leakage fix

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy
This change makes the role sync process stream and process the data from Redis incrementally. Previously it would cache the entire data set before processing which would cause `fiat` to consume a large amount of heap on some data sets.
May fix spinnaker/spinnaker#6328 and fix spinnaker/spinnaker#6319
=> fix(redis): stream read from Redis

fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy, fiat-roles/fiat-roles.gradle, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-web/fiat-web.gradle, fiat-web/src/test/groovy/com/netflix/spinnaker/config/RedisContainerConfig.groovy
Update integration tests to use testcontainer to managed Redis instances. This allows for development to be done on Windows machines.
=> chore(redis): use testcontainer for Redis tests

fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/BaseAccessControlled.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/BuildService.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ResourceType.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ServiceAccount.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultFallbackPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ApplicationResourcePermissionSource.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ChaosMonkeyApplicationResourcePermissionSource.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourcePrefixPermissionSource.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultFallbackPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/ResourcePrefixPermissionSourceSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatServerConfigurationProperties.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
This change reduces the cost of generating the in-memory model for `UserPermission` and can cut sync time substantially for installations with a high number of resources, roles, and users. There should be no compatibility changes.
The primary changes are:
* Pre-compute the hash code for `ResourceType`, `Role`, and `Permission`. These objects are immutable are are treated as such within the code. At scale, the hash computation becomes expensive given the extensive usage of `Map` and `Set`.
* Change the internal representation of the roles associated with an `Authorization` type within `Permission` to be a `Set`. This makes the calculation of effective permissions vastly cheaper as the call to `Collections.disjoint()` can use an optimised path for `Set` rather than iterating over two lists …
=> perf: Reduce Cost Of Sync Process

.github/workflows/release.yml
The jenkins jobs that publish/release spinnaker use tags of this form. See e.g
spinnaker/buildtool@d5ce139/dev/buildtool/spinnaker_commands.py#L295
+
spinnaker/buildtool@d5ce139/dev/buildtool/spinnaker_commands.py#L305
Those jobs currently publish to bintray, but since that is going away, let's publish to nexus.
=> fix(build): release version tags

fiat-sql/fiat-sql.gradle, fiat-sql/src/test/kotlin/com/netflix/spinnaker/fiat/permissions/SqlPermissionsRepositoryTests.kt, fiat-web/src/test/resources/fiat-test.yml
This works with testcontainers 1.15.1, but also with 1.16.2, where 1.16.2 [broke before this](https://github.com/spinnaker/fiat/runs/4218090381?check_suite_focus=true).
=> Fix testcontainers jdbc urls

fiat-web/config/fiat.yml
This change removes the configuration key `endpoints.health.sensitive`
from `fiat.yml` as it's no longer supported.
Currently when starting Fiat the following message is printed:
```
The use of configuration keys that are no longer supported was found in the environment:
Property source 'applicationConfig: [classpath:/fiat.yml]':
Key: endpoints.health.sensitive
Line: 13
Reason: Endpoint sensitive flag is no longer customizable as Spring Boot no longer provides a customizable security auto-configuration .
```
With this change that message is no longer printed.
=> fix(config): Remove unsupported config keys

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsRepository.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-sql/src/main/kotlin/com/netflix/spinnaker/fiat/permissions/SqlPermissionsRepository.kt, fiat-sql/src/test/kotlin/com/netflix/spinnaker/fiat/permissions/SqlPermissionsRepositoryTests.kt, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
The permission rebuild process during role synchronization only requires
the set of roles that each user has. This change modifies the SQL and
Redis `PermissionRepository` instances to only return the roles.
For our use case this drops about 2 minutes of the sync time (so from 3 minutes to 1 minute).
=> fix: improve performance of role sync with SQL

build.gradle, fiat-api/fiat-api.gradle, fiat-bom/fiat-bom.gradle, fiat-github/fiat-github.gradle, fiat-roles/fiat-roles.gradle, fiat-web/fiat-web.gradle, gradle.properties
There is an issue in the Plugins Framework that was solved in this PR: spinnaker/kork#866
but this fix was released in kork 7.110.0
I bumped the version of kork to include the fix in VersionManager in the plugins framework but this involved changing the groupId of kork because now it's been published under "io.spinnaker" and this release branch is pretty old.
I had to bump the version of Fiat as well because it has issues when trying to download the kork version in fiat due to the groupId change.
=> fix(build): bump kork to 7.110.0, change groupId fro dependencies

fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GithubTeamsUserRolesProvider.java, fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/client/GitHubClient.java
re: https://github.com/spinnaker/fiat/pull/907
New API uses team slug instead of ID, see: https://docs.github.com/en/rest/reference/teams#list-team-members
=> fix(gitub): using team slug instead of id

.github/workflows/bump_dependencies.yml
to avoid a hard-coded 10 minute timeout.  See
e.g. https://github.com/spinnaker/bumpdeps/blob/c5ca595ec6211aae4160c46a14a4f2fd04359638/src/main/kotlin/io/spinnaker/bumpdeps/Main.kt#L128
=> chore(build): specify an artifact for bumpdeps to look for

build.gradle
The root cause of this issue is uncontrolled conflict resolution of jackson-bom and kotlin-bom dependency version imported from external maven BOM provided by kork-bom, as per the gradle documentation here (https://docs.gradle.org/6.9.1/userguide/platforms.html#sub:bom_import), we can use gradle enforcedPlatform closure as part of the implementation to strictly adhere the versions of direct and transitive dependencies imported BOM. This approach could be considered as optimally feasible fix for this issue. And for upcoming upgrades and developments, it will also ensure the predictable dependency imports from kork-bom.
Similar issue has been encountered while upgrading spring-boot to 2.3.x for gate service, for detailed discussion please refer to: …
=> fix(dependency): Issue with jackson-bom and kotlin-bom version conflict resolution while upgrading the spring-boot 2.3.x

fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/AccountManagerConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy
This adds a Fiat configuration option for the Account Management API in Clouddriver for listing which roles are allowed to manage accounts in the API.
This option was requested during the initial phase of development for the API. We'll need a Fiat release cut in order to use the changes in Clouddriver, however.
=> feat(core): Add account manager roles config

fiat-github/fiat-github.gradle
While upgrading spring cloud to Hoxton.SR12, we encountered below errors :
```
> Task :fiat-github:compileJava FAILED
/fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java:3: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Max;
^
/fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java:4: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Min;
^
/fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java:5: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;
^
/fiat/fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubPr …
```
=> fix(dependency): Issue of missing javax.validation:validation-api dependency while upgrading the spring cloud to Hoxton.SR12 in kork

fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java, fiat-google-groups/src/test/groovy/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProviderSpec.groovy
Currently the google roles provider checks Google Groups for all service accounts, this is impossible to succeed because these are not real domains usable in Google Groups. This causes a couple of issues around rate limiting due to bad requests, and artificially increases the load on the Admin Directory API quota. By skipping over this without hitting Google we reduce the time needed to check permissions for this, and improve stability of this API
=> fix(google): skip groups for service accounts

.github/workflows/bump_dependencies.yml
Halyard releases are different and release-* branches have no connection
with Spinnaker service releases.
We only want to bumpdep Halyard if tag was pushed to `master` branch.
For services we always want to bumpdep same branch.
=> fix(ci): Only bumpdep Halyard for master branch

fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/AuthenticatedRequestAuthenticationConverter.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConverter.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationFilter.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatClientConfigurationProperties.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatStatus.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/AccessControlledResource.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatSharedSpecification.groovy, fiat-core/fiat-core.gradle, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/Authorization.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/SpinnakerAuthorities.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java, fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java, fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/UserPermissionTest.java
This implements a few relevant Spring Security features and updates Fiat to use them in addition to the newly added AccessControlled interface in Kork.
- Introduces Spinnaker-specific GrantedAuthority values for admins, account managers, and anonymous users.
- Adds conversion from a user's set of roles to a set of granted authorities based on Spring Security conventions (`ROLE_foo` style authorities).
- Adds an implementation for FiatPermissionEvaluator::hasPermission for checking permissions on AccessControlled objects.
- Updates to Permissions/UserPermission to support GrantedAuthority conversions and checks.
- Adds spring-security-core as an API dependency to fiat-core as we now reference GrantedAuthority, Authentication, and some other core security interfaces.
- Updates Authorization …
=> feat(api): Add support for more Spring Security APIs

fiat-sql/src/main/resources/db/changelog-master.yml, fiat-sql/src/main/resources/db/changelog/20220727-resource-name-to-lower-case.yml
Add migration to ensure consistency between resource_name in fiat_resource and fiat_permission tables.
**References:**
* https://github.com/spinnaker/fiat/pull/963
=> fix: add migration to ensure consistency between resource_name in fiat_resource and fiat_permission tables

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/Synchronizer.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncStrategy.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
Hi team,
As prefaced on [Slack](https://spinnakerteam.slack.com/archives/C091CCWRJ/p1656558976174469), we have been running our own Spinnaker cluster for a while, and recently we've noticed that saving service accounts have been timing out from front50 to fiat. We discovered that this was because Fiat runs a sync across all users with the associated roles for the requested service account upon every save, which means for a relatively large user base, this operation results in well over 20s of runtime. 
We ran rudimentary investigation and found that this user role sync does not seem to be necessary for saving these service accounts, since scheduled syncs will straighten out any missing users recently added to this role on the next run. 
Following this train of thought, I'm raising this …
=> perf(serviceAccounts): allows syncing service accounts without resolving user roles

fiat-roles/fiat-roles.gradle, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/ResourceProviderConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationResourceProvider.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverApplicationLoader.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverService.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy, fiat-roles/src/test/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverApplicationLoaderTest.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java
During heavy load, loading applications from Clouddriver causes Spinnaker logins to timeout. During the login flow, Fiat invokes a roles/sync request which causes it to fetch all applications from Clouddriver and Front50 to figure out which applications the user has permissions for. Sometimes, due to heavy load, Clouddriver takes a long time to provide this list of applications(6 - 8.5 mins as seen in our production instances) which causes the aforementioned login timeouts. Front50 is enough to figure out user permissions. So this PR provides a way to optionally turn off querying clouddriver for applications during the roles sync. By default, querying clouddriver for applications is enabled. Users can opt out of it by setting:
```
resource:
provider:
clouddriver:
loadApplications: false …
```
=> feat(roles): add capability to control querying clouddriver for applications during roles sync

.github/workflows/bump_dependencies.yml
To fix
```
Run REPOS=clouddriver,echo,front50,gate,igor,keel,orca
/home/runner/work/_temp/8d0ae0e7-a4c8-4d0d-9869-dafd99934f6c.sh: line 2: [: missing `]'
```
from e.g. https://github.com/spinnaker/fiat/actions/runs/3048063150/jobs/4912729065
=> fix(gha): fix syntax error in code that determines what repos to bump

.github/workflows/bump_dependencies.yml
Somehow ended up with an extra space in the string to match.
From: https://github.com/spinnaker/fiat/actions/runs/3048395605/jobs/4913412198
```
if [ " origin/master" == "  origin/master" ]; then
```
=> fix(gha): Event branch doesn't match

.github/workflows/release.yml
Default timeout (60 seconds from [here](https://github.com/spinnaker/spinnaker-gradle-project/blob/53a9aee82334c282f0ca790d4bf647a238463093/spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/artifactregistry/ArtifactRegistryPublishExtension.groovy#L42)) isn't enough.  See
```
Execution failed for task ':fiat-web:publishDebToArtifactRegistry'.
> java.io.IOException: Operation timed out importing debian package to Artifact Registry.
```
from https://github.com/spinnaker/fiat/actions/runs/3490486645/jobs/5841980754 and https://github.com/spinnaker/fiat/actions/runs/3490766675/jobs/5842611725.
=> chore(build): set timeout for apt publishing to 5 minutes

.github/workflows/release.yml
5 minutes wasn't enough in https://github.com/spinnaker/fiat/actions/runs/3491447692/jobs/5844087369
=> chore(build): set timeout for apt publishing to 10 minutes and add --stacktrace

fiat-sql/src/main/kotlin/com/netflix/spinnaker/fiat/permissions/SqlPermissionsRepository.kt
This fixes a couple issues in the existing implementation of getUserPermission. First, the account manager flag is queried at the same time as the admin flag (which is now fixed thanks to better understanding of the jOOQ API). Secondly, the functions to fetch resources for a given user were doing a natural join in Kotlin rather than offloading the request to the database to join.
=> refactor(sql): Optimize read queries for getUserPermission

fiat-sql/src/main/kotlin/com/netflix/spinnaker/fiat/permissions/SqlPermissionsRepository.kt, fiat-sql/src/test/kotlin/com/netflix/spinnaker/fiat/permissions/SqlPermissionsRepositoryTests.kt
After the update to make all resource names lowercase, the user role sync process deletes the permission if the resource name (provided by the ResourceProvider) is in uppercase and the one in DB is in lowercase.
=> fix: Should fix the deletion of permissions when resource name is uppercase

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/FiatRoleConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/Synchronizer.java
Spring refuses to start due to a missing bean when write mode is disabled. The roles sync should not be enabled at all when write mode is disabled, so this fix disables both sync strategies and the Synchronizer class if read mode is disabled. Fixes bug introduced in https://github.com/spinnaker/fiat/pull/962.
Error message:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 0 of constructor in com.netflix.spinnaker.fiat.roles.Synchronizer required a bean of type 'com.netflix.spinnaker.fiat.config.ResourceProvidersHealthIndicato>
Action:
Consider defining a bean of type 'com.netflix.spinnaker.fiat.config.ResourceProvidersHealthIndicator' in your configuration.
```
=> fix(fiat-roles): Fiat fails to start if write mode is disabled

build.gradle, fiat-api/fiat-api.gradle, fiat-roles/fiat-roles.gradle, fiat-sql/fiat-sql.gradle
Spring boot 2.4.x removed JUnit5 vintage engine from [spring-boot-starter-test](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test). It is required for executing junit4 based test cases in fiat. So, introducing junit-vintage-engine dependency in build.gradle, using testRuntimeOnly() as suggested in section 3.1 of https://junit.org/junit5/docs/5.6.2/user-guide/index.pdf
After applying this fix, coverage increased from 87 to 180 test case executions.
=> fix(tests): Introduce junit5 vintage engine for running junit4 test cases over junit5 in fiat

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandler.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/HeadersRedactor.java, fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandlerSpec.groovy, fiat-api/src/test/java/com/netflix/spinnaker/fiat/shared/HeadersRedactorTest.java
Redacted secret data from log in `FiatAccessDeniedExceptionHandler`. 
```
17:59:18.180 [Test worker] ERROR com.netflix.spinnaker.fiat.shared.FiatAccessDeniedExceptionHandler - Encountered exception while processing request : with headers={Authorization=bearer **REDACTED**, X-Frame-Options=**REDACTED**, Content-Type=text/html}
org.springframework.security.access.AccessDeniedException: Forbidden
```
=> fix(logs): Redacted secret data in logs.

fiat-api/fiat-api.gradle, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java, fiat-github/fiat-github.gradle, fiat-github/src/main/java/com/netflix/spinnaker/fiat/config/GitHubConfig.java, fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GithubTeamsUserRolesProvider.java, fiat-web/fiat-web.gradle, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java
This pull request registers `SpinnakerRetrofitErrorHandler` with each `Retrofit.RestAdapter` and replaces each `RetrofitError` catch block with a catch-block using `SpinnakerServerException` or the appropriate subclass. This is part of an effort to consume `SpinnakerRetrofitErrorHandler` in each Spinnaker microservice, as detailed in [issue #5473](https://github.com/spinnaker/spinnaker/issues/5473)
=> feat(exceptions): Add SpinnakerRetrofitErrorHandler and replace RetrofitError catch blocks

.github/workflows/build.yml, .github/workflows/bump_dependencies.yml, .github/workflows/pr.yml, .github/workflows/release.yml
to avoid warning messages like
Run echo ::set-output name=REPO::${GITHUB_REPOSITORY##*/} Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore(gha): replace deprecated set-output commands with environment files

fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy, fiat-web/src/test/groovy/com/netflix/spinnaker/config/RedisContainerConfig.groovy
so that uses in a private registry (e.g. via TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX) work.  Uses via docker.io continue to work.
For example:
```
$ docker pull redis:5-alpine
5-alpine: Pulling from library/redis
Digest: sha256:1a3c609295332f1ce603948142a132656c92a08149d7096e203058533c415b8c Status: Image is up to date for redis:5-alpine
docker.io/library/redis:5-alpine
```
```
$ docker pull docker.io/redis:5-alpine
5-alpine: Pulling from library/redis
Digest: sha256:1a3c609295332f1ce603948142a132656c92a08149d7096e203058533c415b8c Status: Image is up to date for redis:5-alpine
docker.io/library/redis:5-alpine
```
```
$ docker pull docker.io/library/redis:5-alpine
5-alpine: Pulling from library/redis
Digest: sha256:1a3c609295332f1ce603948142a132656c92a08149d7096e203058533c415b8c Status: Image …
```
=> refactor(test): prefix redis:5-alpine images with library/

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/ResourceProviderConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationResourceProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy
- This PR allows skipping Application.details while caching the UserPermission.
- This is an opt-in feature which can be enabled by the following configuration:
```yaml
resource:
provider:
application:
suppressDetails: true
```
- Fixes the issue:  https://github.com/spinnaker/spinnaker/issues/6842
=> feat(fiat): Suppress application details when updating permissions

fiat-ldap/fiat-ldap.gradle, fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/config/LdapConfig.java, fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java, fiat-ldap/src/test/groovy/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProviderTest.groovy
Addresses https://github.com/spinnaker/spinnaker/issues/6841
- The PR allows for getting Ldap memberships for large number of users
- Pagination support while fetching group memberships
- Support for user IDs to user DNs mapping provided using batched LDAP queries
- This is an opt-in feature using the below configuration:
```
auth:
groupMembership:
ldap:
enableDnBasedMultiLoad: true
```
And to enable pagination, below configuration is also needed:
```
auth:
groupMembership:
ldap:
enablePagingForGroupMembershipQueries: true
```
=> feat(ldap): Support for handling DN based multiloaded roles

fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/config/LdapConfig.java, fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java, fiat-ldap/src/test/groovy/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProviderTest.groovy, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/UserRolesProviderCacheConfig.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/BaseUserRolesProvider.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/BaseUserRolesProviderSpec.groovy
* BaseUserRolesProvider: New class to enable caching layer for concrete UserRolesProvider implementations.
* LdapUserRolesProvider: Update class to consume caching layer.
* When call for roles is initiated, now the local cache responds with cached roles else LDAP is contacted and the result gets cached.
* This feature can be enabled by adding the below configuration:
```yaml
auth:
groupMembership:
ldap:
cache:
enabled: true
expireAfterWriteSeconds: 600        
```
* Cached entries expire after `expireAfterWriteSeconds` seconds. This is an optional configuration whose default value is 600(i..e, 1hour).
* Addressed the spinnaker issue: https://github.com/spinnaker/spinnaker/issues/6845
=> feat(fiat) - Cache fetched LDAP roles to speed up role syncs.

fiat-roles/fiat-roles.gradle, fiat-roles/src/test/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverApplicationLoaderTest.java, fiat-web/src/test/groovy/com/netflix/spinnaker/config/FiatSystemTest.java, fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/MainSpec.java
Before refactor, total test cases executed were 195. 
After refactor, total test cases executed are 195.
=> refactor(tests): convert junit4 based testcases to junit5 and clean up in fiat

fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java
Because of the use of parallelStream to add elements to HashMap, the result is not always reliable due to non-thread-safe nature and occasional  InvalidCacheLoadException is observed. Hence removed parallelStream.
=> fix(ldap): fixed sporadic occurrence of InvalidCacheLoadException

fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/CallableCache.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncStrategy.java, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/CachedSynchronizationSpec.groovy, fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/CallableCacheSpec.groovy
This PR addresses: https://github.com/spinnaker/spinnaker/issues/6856
Made sure the calls to CallableCache are null-free to prevent NullPointerExceptions.
=> fix(roles-sync): fix CallableCache's NPE exception for caching synchronization strategy

fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/RetrofitConfig.java
This change removes unused deprecated class. Its instantiation caused fiat to fail when configuring SSL. Other then fixing an issue, the class was never used.
Tested on local environment on fiat 1.29.x, master and 1.30.x.
Before this change:
* fiat was throwing FileNotFound because OkHttpClientConfigurationProperties were not decrypted
* the properties were not decrypted and the key-store could not be downloaded into a file
* this happened because  okHttpClientConfig instantiated OkHttpClientConfigurationProperties before the SecretBeanPostProcessor was instantiated
After the change:
* SecretBeanPostProcessor is instantiated first
* then it is used when OkHttpClientConfigurationProperties is instantiated  to decrypt each property
=> fix(ssl): Removed unused deprecated okHttpClientConfig from retrofitConfig.

fiat-web/fiat-web.gradle
since it's meant for migration only
See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#configuration-properties for background.
=> chore(dependencies): remove org.springframework.boot:spring-boot-properties-migrator

fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java, fiat-ldap/src/test/groovy/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProviderTest.groovy
It has been observed that when a user has multiple entries in LDAP the resulting roles set for that user is empty. 
This  PR addresses the issue by merging the unique roles associated with all the entries for that user.
Before adding the changes, I have updated the existing tests to strengthen the assertions and included a test demonstrating the issue.
=> fix(ldap/roles): fix the issue of multiple entries in Ldap for single user

fiat-roles/fiat-roles.gradle, fiat-web/fiat-web.gradle
All references to com.squareup.okhttp will be removed with this PR.
Refer https://github.com/spinnaker/kork/pull/1210 for kork PR which completes the removal of okhttp2 dependencies.
=> fix(retrofit): remove all com.squareup.okhttp dependencies

fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationConfig.java, fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatService.java, fiat-core/fiat-core.gradle, fiat-core/src/main/java/com/netflix/spinnaker/fiat/util/RetrofitUtils.java, fiat-github/fiat-github.gradle, fiat-github/src/main/java/com/netflix/spinnaker/fiat/config/GitHubConfig.java, fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/client/GitHubClient.java, fiat-github/src/test/java/com/netflix/spinnaker/fiat/roles/github/GithubTeamsUserRolesProviderTest.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverApi.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/Front50Api.java, fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/IgorApi.java, fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java
- When a retrofit client baseUrl has multiple slashes(ex: `https://somehost/api/v3/`), the resulting url changes based on the whether there is a leading slash in the endpoint or not. If the endpoint is prefixed with a `/` (ex: `/orgs/{org}/members`) the resulting url omits the segment post first `/` from baseUrl.  
- The example above results in `https://somehost/orgs/someorg/members` instead of `https://somehost/api/v3/orgs/someorg/members`. 
- This PR addresses the issue by removing the leading `/` from all the endpoints and making sure the baseUrl ends with a trailing `/`
- A test is added to demonstrate the issue.
=> fix(retrofit2): fix multiple slash issue in baseUrl of retrofit2 client
