spinnaker/fiat

- README.md
As requested by the community.
@spinnaker/netflix-reviewers, @spinnaker/google-reviewers, @gbougeard FYI.
> Adds roadmap/punchlist of TODOs

- fiat-core/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsRepository.java
- fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
> Stoopud javadoc

- README.md
@spinnaker/google-reviewers @gbougeard  FYI
> Updates punchlist

- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/ControllerSupport.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
> URLDecode usernames on controllers

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/ServiceAccount.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/GroupAccessControlled.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Resource.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ResourceType.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Viewable.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/AccountProvider.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/ApplicationProvider.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultAccountProvider.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultApplicationProvider.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProvider.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/GroupAccessControlledResourceProvider.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/ResourceProvider.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/providers/ServiceAccountProvider.java
- fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/ResourceSpec.groovy
- fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultAccountProviderSpec.groovy
- fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy
- fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProviderSpec.groovy
- fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java
- fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
- fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
As discussed with @jtk54 
This will be helpful with https://github.com/spinnaker/fiat/issues/29
> Google resource hierarchy

- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
> Make sync call have optional body

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/github/GithubTeamsUserRolesProvider.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/github/client/GitHubClient.java
@ttomsu if you have any hint/idea to add some integration tests :)
> Closes https://github.com/spinnaker/fiat/issues/59

- fiat-api/src/main/java/com/netflix/spinnaker/config/FiatAuthenticationConfig.java
- fiat-api/src/main/java/com/netflix/spinnaker/config/FiatConfigurationProperties.java
@jtk54 @duftler @gregturn PTAL
> Wraps up some fiat-api configs into a bean

- fiat-github/src/main/java/com/netflix/spinnaker/fiat/config/GitHubConfig.java
> Hooks Github Retrofit client to the system wide logging level.

- fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
> Prevent NPE if user has no groups

- fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatServerConfigurationProperties.java
> Fix typo in sync delay

- build.gradle
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy
> Fixes issue where tests weren't compiling

- fiat-web/fiat-web.gradle
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/FiatSystemTestSupport.groovy
Please review the **last commit only**.
@jtk54 @duftler @lwander PTAL
> Adds a second round of system tests, this time testing the authorize endpoint.

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
- fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
> Fix some NPEs my testsers have found.

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsRepository.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/RolesControllerSpec.groovy
> Adds the unrestricted user when updating subsets of users by role.

- fiat-api/src/main/java/com/netflix/spinnaker/config/FiatAuthenticationConfig.java
- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAuthenticationFilter.java
- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
> Debug message tweaks and some code formatting before next release

- build.gradle
@duftler @jtk54 @cfieber @ajordens PTAL
> Fiat: Bumps spinnaker-dependencies version

- fiat-api/src/main/java/com/netflix/spinnaker/config/FiatClientConfigurationProperties.java
@jtk54 FYI. Current Gate .deb package is broken, so I'm going to submit this and cut a release
> Rm component

- build.gradle
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/Main.java
> Upgrades to Spring Boot 1.4 by way of a spinnaker-deps bump

- build.gradle
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/Main.java
@jtk54 PTAL
@ewiseblatt @cfieber FYI
> Rolls deps version forward, which pulls back Spring Boot back to 1.2.8

- build.gradle
- fiat-web/fiat-web.gradle
@ttomsu 
I added some standard logic for determining whether or not you need mavenLocal. This is the same logic that is now in every other project (the heuristic earlier this week).
> Added stackdriver.

- fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
> Adds logging to google group callback.

- build.gradle
- fiat-web/fiat-web.gradle
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
@ewiseblatt @jtk54 @duftler PTAL
> Adds spectator integration for metrics collection.

- fiat-core/fiat-core.gradle
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java
- fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/ApplicationSpec.groovy
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/providers/DefaultApplicationProviderSpec.groovy
Fixes https://github.com/spinnaker/fiat/issues/125
PTAL @duftler @jtk54
> Ensure requiredGroupMembership value is never null

- fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GithubTeamsUserRolesProvider.java
- fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java
@jtk54 @duftler PTAL
cc @msloes
> Added more logging during user role sync

- fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GithubTeamsUserRolesProvider.java
- fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/client/GitHubClient.java
> Adds pagination support to Github UserRolesProvider

- halconfig/fiat.yml
> Base fiat halconfig

- fiat-api/src/main/java/com/netflix/spinnaker/config/FiatAuthenticationConfig.java
> Turns on READ_UNKNOWN_ENUM_VALUES_AS_NULL

- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ServiceAccount.java
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy
Fixes https://github.com/spinnaker/fiat/issues/140
@jtk54 PTAL
> Force lower case for all group membership data types.

- build.gradle
- cloudbuild.yaml
@cfieber PTAL
cc @duftler @skim1420
> Gradle project version bump + cloudbuild trigger

- cloudbuild.yaml
> Use commit SHA as label in cloudbuild.yaml

- gradle/buildViaTravis.sh
> Ignore Spinnaker product tag patterns in TravisCI.

- Dockerfile.slim
- cloudbuild.yaml
Shrinks super slim container down to 78MB
@duftler @skim1420 FYI
> Google Cloud Builder optimizations

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
@jtk54 @cfieber FYI. This'll need to be released and each component version bumped (again. ugh.)
> fix(api): Catch additional UncheckedExecutionException in cache loading

- fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
- fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
I realized this essential and core function didn't have a test :open_mouth:
> chore(tests): Adds simple test for hasPermission function

- fiat-core/src/test/groovy/com/netflix/spinnaker/fiat/model/resources/PermissionsSpec.groovy
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
tag: https://github.com/spinnaker/fiat/issues/179
> fix(logging): Adds some extra logging to /roles/sync invocation

- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java
- fiat-file/fiat-file.gradle
- fiat-file/src/main/java/com/netflix/spinnaker/fiat/roles/file/FileBasedUserRolesProvider.java
- fiat-file/src/test/groovy/com/netflix/spinnaker/fiat/roles/file/FileBasedUserRolesProviderSpec.groovy
- fiat-file/src/test/resources/fiat-test-permissions.yml
- fiat-web/fiat-web.gradle
- settings.gradle
> feat(permissions): Add ability to specify permissions in a file, rather

- fiat-ldap/fiat-ldap.gradle
- fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java
> fix(ldap): Bump LDAP lib version

- fiat-github/src/main/java/com/netflix/spinnaker/fiat/roles/github/GitHubProperties.java
> fix(authz/github): Default cache TTL

- fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
Adding some backoff to user group queries.
> Add backoff and rety to GCP directory listings.

- fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
Google returns a 403 on rate limit exceeded and the default retry only occurs on server 500s. However, this results in users intermittently loosing their authorities/roles in Fiat as only a partial list can be obtained.
> Back off on 500's or 403 rate limits.

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/CatsSchedulerConfig.java
- fiat-web/lib/systemd/system/fiat.service
Added systemd service configuration for fiat.
> feat(xenial_builds): Added systemd service configuration for fiat.

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
if we lose the redis data the user roles syncer would no longer reload the anonymous
permissions.
also this caps the number of retries that the refresh will do to something that aligns with
the caching agents timeout value. The agent will get rescheduled after that point by the
scheduler.
> fix(roles): ensure UserRolesSyncer always refreshes anonymous user

- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java
> fix(admin): Admin parameter in accounts not being passed properly.

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/UserRolesSyncerSpec.groovy
If discovery is not available, the `UserRolesSyncer` will be enabled
and run as expected.
Follows a similar pattern used in other services.
> feat(core): User role syncing should pause when not in discovery

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatStatus.java
Correct a typo in the expected dynamic property name.
> fix(core): s/legacyFallback/fiat.legacyFallback

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/ClouddriverService.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java
s/s.fiat.getUserPermissionCounterId/fiat.getUserPermission
> feat(logs): Bit of logging when permissions are updated

- fiat-roles/fiat-roles.gradle
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/DynomiteConfig.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepositorySpec.groovy
Quick implementation for dynomite. How do key changes impact things in fiat? Will things just move along ok, or do I need to come up with a key migration story (done this before).
> feat(roles): Adding dynomite support

- build.gradle
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …
> fix(ldap): Fixed UnsupportedOperationException for service accounts which DO NOT exist in User Role Provider Service

- build.gradle
- fiat-web/fiat-web.gradle
- gradle/buildViaTravis.sh
- gradle/init-publish.gradle
- gradle/installViaTravis.sh
Remove spring boot plugin.
Ref: https://github.com/spinnaker/spinnaker/issues/2844
> chore(builds): Introduces composite builds via gradle plugin.

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
This was causing the `roles/sync` endpoint to timeout when there were a large number of service accounts. 
e.g.: https://github.com/spinnaker/spinnaker/issues/3562
> fix(sync): Stop syncing service accounts in roleProvider

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
> Revert "fix(sync): Stop syncing service accounts in roleProvider"

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
This reverts commit 8968304c832772d1e92c90675d9f15faca116987.
> Revert "fix(sync): Stop syncing service accounts in roleProvider (#289)"

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolverSpec.groovy
Attempt 2. This time around, I added the logic to remove service account users from the list of users passed in to `resolve`. For service accounts, we skip the call to fetch roles but resolve resources for the given roles.
> fix(sync): Resolve service accounts without role provider calls.

- fiat-google-groups/fiat-google-groups.gradle
Addresses spinnaker/spinnaker#3598
> chore(google): Update google API dependencies

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/UserPermission.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/BuildService.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ResourceType.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultBuildServiceProvider.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/IgorApi.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/internal/IgorService.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java
- fiat-web/src/test/groovy/com/netflix/spinnaker/config/ResourceConfig.groovy
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/RolesControllerSpec.groovy
- fiat-web/src/test/resources/fiat.properties
See https://github.com/spinnaker/igor/pull/374 for the description
> feat(buildservices): Permission support for build services (CI's)

- fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/ResourcesConfig.java
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/MainSpec.java
- fiat-web/src/test/resources/fiat-test.yml
Similar to https://github.com/spinnaker/gate/pull/774
> test(core): Add a basic startup test.

- fiat-web/fiat-web.gradle
Prereq for spinnaker/kork#273 merge
> chore(dependencies): ensure direct dependency on kork-secrets-aws

- fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
Ran it 100 times without failure!
> fix(test): Fix flaky test by setting cache expire immediately after write

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
This PR preserves the debouncing capability of the existing
`permissionsCache` but attempts to provide a fresher fallback in the
event that a "no accounts" fallback was previously cached.
The "no accounts" fallback will result if the `X-SPINNAKER-*` headers
are not propagated for a given api request (or that api request
originated from an scheduled system operation and thus was not
authenticated to begin with).
Ported from the v0.63.x branch.
> fix(api): Rebuild the legacy fallback if it has no account grants

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java
> feat(api): Log any access granted as part of a legacy fallback.

- build.gradle
- fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluatorSpec.groovy
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountProvider.java
- gradle.properties
updates kork to 5.3.4
updates spinnaker-gradle-plugin to 6.5.0
> chore(dependencies): externalize versions to properties

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultPermissionsResolver.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/PermissionsResolver.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseProvider.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourceProvider.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
Cherry pick of https://github.com/spinnaker/fiat/pull/409
> fix(apps): Clear resource provider caches to ensure up-to-date data

- fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/RetrofitConfig.java
- gradle.properties
fixes okhttp interceptor constructor
> chore(dependencies): kork 5.4.8

- build.gradle
- fiat-bom/fiat-bom.gradle
- settings.gradle
This simplifies dependency resolution downstream
> feat(fiat-bom): publish fiat-bom

- fiat-web/fiat-web.gradle
Fixing fiat so that it emits json logs.
> fix(logs): add logback-encoder to classpath

- fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandler.java
- fiat-api/src/test/groovy/com/netflix/spinnaker/fiat/shared/FiatAccessDeniedExceptionHandlerSpec.groovy
Small improvement to readability ("service account" instead of "serviceaccount") and additional tests.
> fix(error): Test various access denied scenarios and improve readability

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/Main.java
- fiat-web/src/test/groovy/com/netflix/spinnaker/config/EmbeddedRedisConfig.groovy
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
- gradle.properties
See https://github.com/spinnaker/spinnaker/issues/5134
Dependent on https://github.com/spinnaker/kork/pull/419 for a Spring Boot dependency upgrade
> chore(dependencies): Upgrade Spring Boot to 2.2.1

- Dockerfile.slim
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Permissions.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/DefaultFallbackPermissionsResolver.java
> chore(permissions): Add unpack() public method to Permissions

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/Main.java
- fiat-web/src/test/groovy/com/netflix/spinnaker/config/EmbeddedRedisConfig.groovy
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/controllers/AuthorizeControllerSpec.groovy
- gradle.properties
Revert "chore(dependencies): Upgrade Spring Boot to 2.2.1 (#510)"
This reverts commit d798ec07
> chore(dependencies): Reverting Spring Boot 2.2 upgrade

- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Account.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Application.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java
- fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/ServiceAccount.java
missing types on extended generic typed class
override annotations on overridden method
> chore(cleanup): fix some minor inconsistencies

- .github/workflows/build.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- gradle.properties
Also took the opportunity to rename some things in github action workflows.
> chore(build): Bump spinnaker-gradle-project version

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/ResourceProvidersHealthIndicator.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ProviderHealthTracker.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/UserRolesSyncer.java
additional metrics around UserRolesSyncer timing
additional metrics on ResourceProvidersHealthIndicators
update ResourceProviderHealthIndicators to not go out of service
once a resource has successfully loaded
> feat(ops): operational improvements

- fiat-api/fiat-api.gradle
An upcoming kork bump will move some dependencies from api to
implementation; update places that were depending on the api
dependency to include it explicitly.
> refactor(core): Clean up dependencies

- .github/workflows/build.yml
- .github/workflows/bump_dependencies.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/release_info.sh
- build.gradle
- fiat-bom/fiat-bom.gradle
- fiat-web/fiat-web.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
this is a work in progress that applies spinnaker/spinnaker-gradle-project#121
> chore(build): update to newer spinnaker project plugin

- .gitignore
- fiat-web/fiat-web.gradle
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
- fiat-web/src/test/groovy/com/netflix/spinnaker/fiat/MainSpec.java
- fiat-web/src/test/resources/fiat.properties
This PR makes Fiat pluggable, similar to spinnaker/clouddriver#4383
> feat(plugins): add plugins to fiat

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/BaseServiceAccountResourceProvider.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/DefaultServiceAccountResourceProvider.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java
introduces BaseServiceAccountResourceProvider to capture service account specific
access checks"
> feat(serviceAccounts): enable customization of service account resource provider

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
- gradle.properties
This includes updates to google-java-format and ktlint, so requires some
formatting changes. These were made with a simple `./gradlew spotlessApply`.
> chore(spotless): upgrade spinnaker gradle plugin

- fiat-roles/fiat-roles.gradle
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/config/PermissionsRepositoryConfig.java
- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
Adds a Configuration class to create RedisPermissionRepository and uses InstrumentedProxy to add
method invocation metrics
> feat(metrics): instrument PermissionRepository

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
Also adds a bunch of logging around the /authorize flow
> fix(perms): adds fallback for fetching unrestricted user

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java
Change the `RedisPermissionsRepository` to use `byte[]` instead of `String` when communicating with Redis. This reduces memory usage with larger permission sets.
> fix(redis): Use byte[] instead of String

- CODEOWNERS
> chore(meta): Remove myself from default reviewers

- .github/workflows/release.yml
to Google Artifact Registry
see: https://github.com/spinnaker/rosco/pull/841
> chore(ci): GHA - indentation consistency

- .github/workflows/bump_dependencies.yml
- .github/workflows/release.yml
Cherry-pick of https://github.com/spinnaker/fiat/pull/934 for release-1.27.x
> feat(build): bump dependencies for the given branch (#934)

- fiat-web/fiat-web.gradle
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/Main.java
Using `com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder` class to setup spring and other related properties required for the spring boot application to start.
> chore(web): clean up for spring property setup

- fiat-roles/src/main/java/com/netflix/spinnaker/fiat/roles/BaseUserRolesProvider.java
- fiat-roles/src/test/groovy/com/netflix/spinnaker/fiat/roles/BaseUserRolesProviderSpec.groovy
Test coverage remain same before and after refactor (Tests executed 197).
> refactor(roles/test): refactor test class functions accessing parent class members

- .github/workflows/build.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- Dockerfile.java11.slim
- Dockerfile.java11.ubuntu
- Dockerfile.slim
- build.gradle
Number 7 on our Java 17 adventure.
See also https://github.com/spinnaker/orca/pull/4604 https://github.com/spinnaker/clouddriver/pull/6113 etc
> feat(java17): use JRE17, run tests on JRE17, compile with JDK11

- fiat-web/fiat-web.gradle
- fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/AuthorizeController.java
- gradle.properties
Depends on https://github.com/spinnaker/kork/pull/1198
> fix(openapi): Rewrite Swagger to OpenAPI annotations
